import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdtemp, writeFile, readFile, mkdir, readdir, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { createServer } from 'node:net';
import assert from 'node:assert/strict';

const root=await mkdtemp(join(tmpdir(),'personas-browser-'));
const release=process.env.PERSONAS_RELEASE;
const binary=resolve(release?join(release,'bin/personas'):'../ai-personas/target/debug/personas');
const assets=resolve(release?join(release,'ui'):'dist');
const fixture=resolve(release?join(release,'integtest/provider_fixture.py'):'../ai-personas/integtest/provider_fixture.py');
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));
const config=join(root,'providers.json');await writeFile(config,JSON.stringify({fixture:['python3',fixture]}));
const child=spawn(binary,['serve','--root',join(root,'node'),'--listen',`127.0.0.1:${port}`,'--providers',config,'--ui',assets],{stdio:['ignore','pipe','pipe']});
let logs='';child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);
let browser; let page;
try {
  let token;for(let i=0;i<100;i++){try{token=await readFile(join(root,'node/token'),'utf8');if((await fetch(`http://127.0.0.1:${port}/health`)).ok)break;}catch{}await delay(50);}
  const base=`http://127.0.0.1:${port}`;const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  async function api(path){const r=await fetch(base+'/api'+path,{headers});assert(r.ok);return r.json();}
  async function op(kind,args,actor='',run=''){const r=await fetch(base+'/api/operations',{method:'POST',headers,body:JSON.stringify({id:crypto.randomUUID().replaceAll('-',''),kind,args,actor,run})});const a=await r.json();assert(r.ok,JSON.stringify(a));assert.notEqual(a.state,'failed',JSON.stringify(a));return a.result;}
  await api('/models');
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.getByLabel('Node token').fill(token);await page.getByRole('button',{name:'Connect to node'}).click();
  await page.getByRole('button',{name:'Personas',exact:true}).click();await page.getByRole('button',{name:'New persona'}).click();await page.getByLabel('Initial model').selectOption({label:'fixture · Protocol fixture'});await page.getByRole('button',{name:'Create',exact:true}).click();await expect(page.getByRole('button',{name:'Unnamed persona',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Environments',exact:true}).click();await page.getByRole('button',{name:'New environment'}).click();await page.getByRole('button',{name:'Create',exact:true}).click();await expect(page.getByRole('button',{name:'Unnamed environment',exact:true})).toBeVisible();
  await page.getByRole('button',{name:/^Work/}).click();await page.getByRole('button',{name:'New work'}).click();await page.getByLabel('Short title').fill('Browser behavior, fresh evidence');await page.getByLabel('Your instructions').fill('Inspect context through the deterministic test provider.');await page.getByLabel('Environment',{exact:true}).selectOption({label:'Unnamed environment'});await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create',exact:true}).click();await expect(page.getByRole('button',{name:'Browser behavior, fresh evidence',exact:true})).toBeVisible();
  let snapshot=await api('/snapshot');const persona=snapshot.records.find(r=>r.kind==='persona');const work=snapshot.records.find(r=>r.kind==='work');const run=snapshot.records.find(r=>r.kind==='run');
  const job=await op('exec',{command:'printf browser-visible-start; sleep 4; printf browser-visible-finish',background:true},persona.id,run.id);
  await page.getByRole('button',{name:'Browser behavior, fresh evidence',exact:true}).click();await page.getByRole('button',{name:/Unnamed persona.*waiting/}).click();await page.locator('summary').filter({hasText:'exec'}).click();await page.getByRole('button',{name:'Follow output'}).click();await expect(page.locator('.output pre')).toContainText('browser-visible-start');await page.getByRole('button',{name:'Close output'}).click();await page.getByRole('button',{name:'Close ✕',exact:true}).click();
  const started=performance.now();for(const name of ['Personas','Environments','Learning','Network','Work']){await page.getByRole('button',{name:name==='Work'?/^Work/:name,exact:name!=='Work'}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();}assert(performance.now()-started<3000,'Navigation blocked during active work');
  await delay(4500);assert.equal((await api('/actions/'+job.job)).state,'succeeded','Closing output cancelled persona job');
  const native=join(root,'native.svg');await writeFile(native,'<svg xmlns="http://www.w3.org/2000/svg" width="480" height="300"><rect width="480" height="300" fill="#dbeaac"/><circle cx="240" cy="150" r="80" fill="#225e4d"/></svg>');
  const art=await op('artifact.publish',{path:native,name:'New test drawing.svg',media_type:'image/svg+xml'},persona.id);await op('submit',{summary:'Fresh drawing for browser loading verification',artifacts:[art.id],documents:[]},persona.id,run.id);
  await page.getByRole('button',{name:'Browser behavior, fresh evidence',exact:true}).click();await page.getByRole('button',{name:/Open artifact/}).click();await expect(page.getByRole('img',{name:'Persona-authored artifact',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close ✕',exact:true}).last().click();await page.getByRole('button',{name:'Close ✕',exact:true}).click();
  const session=await page.context().newCDPSession(page);await session.send('Performance.enable');await session.send('HeapProfiler.collectGarbage');const before=await session.send('Performance.getMetrics');const fdBefore=(await readdir(`/proc/${child.pid}/fd`)).length;
  for(let i=0;i<15;i++){await page.getByRole('button',{name:'Personas',exact:true}).click();await page.getByRole('button',{name:'Unnamed persona',exact:true}).click();await page.getByRole('button',{name:'Close ✕',exact:true}).click();await page.getByRole('button',{name:/^Work/}).click();await page.getByRole('button',{name:'Browser behavior, fresh evidence',exact:true}).click();await page.getByRole('button',{name:/Open artifact/}).click();await expect(page.getByRole('img',{name:'Persona-authored artifact',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close ✕',exact:true}).last().click();await page.getByRole('button',{name:'Close ✕',exact:true}).click();}
  await session.send('HeapProfiler.collectGarbage');const after=await session.send('Performance.getMetrics');const metric=(r,k)=>r.metrics.find(x=>x.name===k).value;assert(metric(after,'JSHeapUsedSize')-metric(before,'JSHeapUsedSize')<5_000_000,'Retained browser heap grew after closing views');await delay(600);assert((await readdir(`/proc/${child.pid}/fd`)).length<=fdBefore+4,'Server retained files after closed artifact views');
  let artifactStarted;const startedPromise=new Promise(r=>artifactStarted=r);await page.route('**/api/artifacts/*',async route=>{artifactStarted();await delay(1500);try{await route.continue();}catch{}});
  await page.getByRole('button',{name:'Browser behavior, fresh evidence',exact:true}).click();await page.getByRole('button',{name:/Open artifact/}).click();await startedPromise;await expect(page.getByRole('button',{name:'Cancel loading'})).toBeVisible();await page.getByRole('button',{name:'Cancel loading'}).click();await expect(page.getByRole('alert')).toContainText('Loading cancelled');await page.getByRole('button',{name:'Close ✕',exact:true}).last().click();await page.getByRole('button',{name:'Close ✕',exact:true}).click();
  await page.screenshot({path:join(root,'work-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(root,'work-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile view overflows');assert.deepEqual(errors,[]);
  const result={status:'passed',binary,assets,runtimeRevision:(await api('/release')).runtime_revision,tested:['browser creation flow','visible command streaming','job survives view close','responsive navigation during execution','lazy artifact loading','slow-load cancellation','15 repeated navigation and artifact cycles','heap and file descriptor release','mobile layout'],heapDelta:metric(after,'JSHeapUsedSize')-metric(before,'JSHeapUsedSize'),fdBefore,fdAfter:(await readdir(`/proc/${child.pid}/fd`)).length,root};await writeFile(join(root,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
} catch(e){await page?.screenshot({path:join(root,'failure.png'),fullPage:true});console.error('Evidence retained at',root);console.error(logs);throw e;} finally {await browser?.close();child.kill('SIGTERM');}
