import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,rm} from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
const port=5198,origin=`http://127.0.0.1:${port}`,owner='a'.repeat(32),node='b'.repeat(32),child='c'.repeat(32),lesson='d'.repeat(32),other='e'.repeat(32);
const card=(id,title)=>({node:{id,revision:1},fragment:{id:lesson,revision:1},title,basis:'tentative',locator:{description:'Find a relevant method'},short_description:'I check the **published pair** before relying on it.'});
const root={focus_card:null,connections:[],items:[card(node,'Check representations')],next:12};
const graph={focus_card:card(node,'Check representations'),connections:[{source:{id:node,revision:1},target:{id:child,revision:1},origin:'authored_condition',relation:'correction',mode:'full',applicability:'not_evaluated',explanation:'I keep the exception with the procedure.',condition:{kind:'always'}}],items:[card(child,'Compare exports')],next:null};
await mkdir('.qa',{recursive:true});const harness='.qa/memory-harness.tsx';
await writeFile(harness,`import {render} from 'preact'; import {useState} from 'preact/hooks'; import {lazy,Suspense} from 'preact/compat'; import {changes} from '../src/api'; import '../src/style.css'; const Graph=lazy(()=>import('../src/MemoryGraph')); (window as any).listeners=0;const add=changes.addEventListener.bind(changes),remove=changes.removeEventListener.bind(changes);changes.addEventListener=(...a)=>{(window as any).listeners++;return add(...a)};changes.removeEventListener=(...a)=>{(window as any).listeners--;return remove(...a)}; function App(){const [show,setShow]=useState(false);return <><button onClick={()=>setShow(!show)}>{show?'Close learning':'Open learning'}</button>{show&&<Suspense fallback={<p>Loading graph</p>}><Graph owner="${owner}" open={()=>{}}/></Suspense>}</>}render(<App/>,document.getElementById('test')!);`);
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(port),'--strictPort'],{stdio:'ignore'});let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:900}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.route('**/memory-fixture',r=>r.fulfill({contentType:'text/html',body:'<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><main id="test" style="padding:12px"></main><script type="module" src="/.qa/memory-harness.tsx"></script></body></html>'}));
 await page.route('**/api/personas/*/memory?*',r=>{const url=new URL(r.request().url());r.fulfill({json:url.searchParams.has('query')?{...root,items:[card(child,'Compare exports')],next:null}:url.searchParams.has('focus')?graph:url.searchParams.get('after')==='12'?{...root,items:[card(other,'A later fragment')],next:null}:root});});
 await page.route('**/api/personas/*/memory/activity?*',r=>r.fulfill({json:{items:[{action:'f'.repeat(32),created:'2026-09-24T00:00:00Z',committed:false,state:'failed',learning:'I wanted to retain a useful check',error:'Current evidence was not received',deferred:[{cue:'Compare exports',reason:'The pair is missing',reconsider_when:'Both outputs arrive'}]}],next:null}}));
 await page.route('**/api/personas/*/memory/usage/*',r=>r.fulfill({json:{selected_participations:1,admitted_calls:2,recent_calls:[]}}));
 await page.route('**/api/records/'+node,r=>r.fulfill({json:{id:node,kind:'memory_node',scope:owner,revision:2,data:{locator:{description:'Find a relevant method',parameters:[{name:'query',description:'Words to match'}],script:'def locate(arguments, nodes):\n    return {"active":[],"focus":None,"after":None}'}}}}));
 await page.route('**/api/records/'+lesson,r=>r.fulfill({json:{id:lesson,kind:'fragment',scope:owner,revision:1,created:'2026-09-24T00:00:00Z',updated:'2026-09-24T00:00:00Z',data:{owner,title:'Check representations',content:'## My check\n\nI compare the exact **published source** with its preview.\n\n<script>window.injected=true</script>',draft:{applicability:'When exporting related outputs',limitations:'This is a synthetic fixture.'},status:'retained'}}}));
 await page.goto(origin+'/memory-fixture');assert(!requests.some(u=>u.includes('MemoryGraph.tsx')));
 await page.getByRole('button',{name:'Open learning',exact:true}).click();await expect(page.getByRole('heading',{name:'Check representations'})).toBeVisible();assert(!requests.some(u=>u.includes('MemoryFragment.tsx')));assert(!requests.some(u=>u.includes('/api/records/'+lesson)));assert(!requests.some(u=>u.includes('MemoryLocator.tsx')));await expect(page.getByText('Idea to test',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'How this finds lessons',exact:true}).click();await expect(page.getByRole('region',{name:'Retrieval utility',exact:true})).toBeVisible();await page.getByText('View utility code · revision 2',{exact:true}).click();await expect(page.locator('.memory-code')).toContainText('def locate');await page.getByRole('button',{name:'Close retrieval utility',exact:true}).click();await expect(page.locator('.memory-locator')).toHaveCount(0);
 await page.getByRole('button',{name:'Read fragment',exact:true}).click();await expect(page.getByRole('heading',{name:'My check',exact:true})).toBeVisible();await expect(page.getByText('Selected in 1 participation.',{exact:true})).toBeVisible();assert.equal(await page.evaluate(()=>window.injected),undefined);
 const expandedListeners=await page.evaluate(()=>window.listeners);
 await page.getByRole('button',{name:'Close fragment',exact:true}).click();await expect(page.locator('.memory-fragment')).toHaveCount(0);assert((await page.evaluate(()=>window.listeners))<expandedListeners);
 await page.getByRole('button',{name:'Explore connections',exact:true}).click();await expect(page.getByRole('heading',{name:'Compare exports',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Authored connections',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'All learning',exact:true}).click();await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(page.getByRole('heading',{name:'A later fragment',exact:true})).toBeVisible();
 await page.getByLabel('Find learning',{exact:true}).fill('export');await page.getByRole('button',{name:'Search learning',exact:true}).click();await expect(page.getByRole('heading',{name:'Matching lessons',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Compare exports',exact:true})).toBeVisible();assert(!requests.some(u=>u.includes('MemoryActivity.tsx')));await page.getByRole('button',{name:'View learning activity',exact:true}).click();await expect(page.getByText('Learning update failed · nothing committed',{exact:true})).toBeVisible();await expect(page.getByText('Both outputs arrive',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to fragment graph',exact:true}).click();await expect(page.getByRole('region',{name:'Learning activity',exact:true})).toHaveCount(0);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.qa/memory-graph-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Close learning',exact:true}).click();await expect(page.getByRole('region',{name:'Fragment graph',exact:true})).toHaveCount(0);assert.equal(await page.evaluate(()=>window.listeners),0);assert.deepEqual(errors,[]);
 console.log('Memory UI passed: lazy graph/detail, readable Markdown, sanitization, directed connections and conditions, pagination, evidence labels, mobile layout and subscription cleanup.');
}finally{await browser?.close();server.kill('SIGTERM');await rm(harness,{force:true});}
