/* Browser-only design surface. Deliberately no fetch, credentials, persistence or provider. */
(function () {
  'use strict';
  const D=globalThis.PersonaDesign;
  let state=D.initialState(),filter='all',workSearch='',personaSearch='',detailTab='overview',workspaceTab='now';
  const app=document.getElementById('app'), dialog=document.getElementById('dialog');
  let opener=null,openerId=null;
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths={work:'<rect x="5" y="5" width="14" height="16" rx="2"/><path d="M9 5V3h6v2M9 10h6M9 14h4"/>',people:'<path d="M16 21v-3a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v3m16 0v-3a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="10" cy="7" r="4"/>',layers:'<path d="m12 3 10 5-10 5L2 8Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>',book:'<path d="M12 5v16M12 5C8 2 4 3 2 4v16c4-2 7-1 10 1 3-2 6-3 10-1V4c-2-1-6-2-10 1Z"/>',settings:'<path d="M3 6h3m4 0h11M3 18h11m4 0h3"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="18" r="2"/>',home:'<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',wave:'<path d="M2 12c3-15 5-15 10 0s7 15 10 0"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',back:'<path d="M19 12H5m6-6-6 6 6 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',question:'<rect x="3" y="3" width="18" height="18" rx="5"/><path d="M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 3h.01"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m8 4 12 8-12 8Z"/>',target:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/>',tool:'<path d="M14 6a5 5 0 0 0-6 6L3 17a3 3 0 0 0 4 4l5-5a5 5 0 0 0 6-6l-4 3-3-3Z"/>'};
  const icon=name=>`<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]||paths.work}</svg>`;
  const brand=()=>'<span class="brand"><span class="brand-mark">ap</span>AI Personas</span>';
  const btn=(text,action,primary=false,extra='')=>`<button class="btn ${primary?'primary':''}" data-action="${action}" ${extra}>${text}</button>`;
  const badge=(text,tone='',dot=false)=>`<span class="badge ${tone}">${dot?'<span class="dot"></span>':''}${escape(text)}</span>`;
  const status=work=>({needs_you:['Needs you','amber'],working:['Working','blue'],waiting:['Awaiting assessment','blue'],paused:['Paused',''],awaiting_acceptance:['Awaiting acceptance','amber']}[work.activity]||['Unknown','']);
  const avatar=(p,size='')=>`<span class="avatar ${escape(p.tone||'sage')} ${size}" aria-hidden="true">${escape(p.initials)}</span>`;
  const group=ids=>`<span class="avatar-group" aria-hidden="true">${ids.map(id=>state.people.find(p=>p.id===id)).filter(Boolean).map(p=>avatar(p,'tiny')).join('')}</span>`;
  const foot=()=>`<footer class="footnote">${icon('info')}<span>Illustrative records · No live providers, generated portraits or verified task results. Changes reset on reload.</span></footer>`;
  const navItems=[['work','Work','work'],['personas','Personas','people'],['environments','Environments','layers'],['learning','Learning','book'],['settings','Settings','settings']];
  function nav(active,mobile=false){return navItems.filter(n=>mobile||n[0]!=='settings').map(([id,label,symbol])=>`<a class="${mobile?'':'nav-item '}${active===id?'active':''}" href="#/${id}" ${active===id?'aria-current="page"':''}>${icon(symbol)}<span>${label}</span>${!mobile&&id==='work'?`<span class="nav-count">${state.works.length}</span>`:''}</a>`).join('');}
  function shell(content,active='work',title='Work') {
    return `<aside class="sidebar"><a href="#/work">${brand()}</a><nav aria-label="Main">${nav(active)}</nav><div class="sidebar-story"><div class="eyebrow muted">A continuing<br>workspace</div><p>Familiar collaborators.<br>Learning with a history.<br>Results with evidence.</p></div><div class="sidebar-end"><a class="nav-item ${active==='settings'?'active':''}" href="#/settings">${icon('settings')}Settings</a><div class="account"><span class="work-symbol">${icon('target')}</span><div><strong>Your workspace</strong><br><span class="muted">Local design preview</span></div></div></div></aside><header class="topbar"><a class="mobile-brand" href="#/work">${brand()}</a><div class="crumb"><span>Your workspace</span><span>/</span><span>${escape(title)}</span></div><div class="preview-label"><span class="dot"></span>Design preview <span class="muted">· Illustrative data, no live providers</span></div></header><main id="main" class="main" tabindex="-1">${content}${foot()}</main><nav class="bottom-nav" aria-label="Mobile main">${nav(active,true)}</nav>`;
  }
  function searchBox(id,placeholder,value){return `<label class="search">${icon('search')}<span class="sr-only">${placeholder}</span><input id="${id}" type="search" placeholder="${placeholder}" value="${escape(value)}" autocomplete="off"></label>`;}
  function requestBanner(w){return `<section class="request-banner" aria-label="Needs your answer"><span class="work-symbol">${icon('question')}</span><div><div class="eyebrow">Needs your answer · ${escape(w.title)}</div><h3>Confirm the site and location</h3><p>Mira needs these details before the team can make site-specific decisions.</p></div>${btn(`Answer request ${icon('arrow')}`,'answer',false,`data-id="${escape(w.id)}" id="answer-banner-${escape(w.id)}"`)}</section>`;}
  function workRow(w){const [label,tone]=status(w);return `<article class="work-row" aria-labelledby="work-title-${escape(w.id)}"><div class="work-identity"><span class="work-symbol">${icon(w.icon)}</span><div><h2 id="work-title-${escape(w.id)}"><a href="#/work/${escape(w.id)}">${escape(w.title)}</a></h2><p class="work-meta">${escape(w.environment)} ${group(w.personas)} ${w.personas.length} personas</p><p class="update"><strong>${escape(w.updateType)}</strong> · ${escape(w.update)}</p></div></div><div class="fact activity-fact"><span class="fact-label">Activity</span><div>${badge(label,tone,true)}<small>${w.request==='open'?'One open request':w.request==='answered'?'Answer recorded, not resolved':'Illustrative activity'}</small></div></div><div class="fact"><span class="fact-label">Latest version</span><div>${escape(w.latest)}<small>Not reviewed</small></div></div><div class="fact"><span class="fact-label">Evidence</span><div>${escape(w.evidence)}<small>No verified results</small></div></div><a class="icon-btn" aria-label="Open ${escape(w.title)}" href="#/work/${escape(w.id)}">${icon('arrow')}</a></article>`;}
  function workList(){const open=state.works.find(w=>w.request==='open');const rows=D.filterWorks(state,filter,workSearch);const counts=[state.works.length,state.works.filter(w=>w.request==='open').length,state.works.filter(w=>w.activity==='working').length];return shell(`<header class="page-heading"><div><h1>Work</h1><p>Your goals, the latest activity, and what needs you.</p></div>${btn(`${icon('plus')}New work`,'new-work',true,'id="new-work"')}</header>${open?requestBanner(open):''}<div class="toolbar"><div class="filters" role="group" aria-label="Filter work">${[['all','All work'],['needs','Needs you'],['progress','In progress']].map(([id,text],i)=>`<button id="filter-${id}" class="filter ${filter===id?'active':''}" data-action="filter" data-filter="${id}" aria-pressed="${filter===id}">${text} <span>${counts[i]}</span></button>`).join('')}</div>${searchBox('work-search','Search work...',workSearch)}</div><section class="work-table" aria-label="Work items"><div class="table-heading" aria-hidden="true"><span>WORK &amp; LATEST ACTIVITY</span><span>ACTIVITY</span><span>LATEST VERSION</span><span>EVIDENCE</span><span></span></div>${rows.length?rows.map(workRow).join(''):'<div class="empty"><h2>No matching work</h2><p class="muted">Try another search or choose All work.</p></div>'}</section><div class="table-foot"><span>${rows.length} work items · Activity is separate from review and evidence.</span><span>All changes preserved in the proposed runtime</span></div><section aria-labelledby="recent-title"><header class="recent-heading"><h2 id="recent-title">Latest in your workspace</h2><span class="eyebrow muted">Sample activity</span></header><div class="recent-row">${avatar(state.people[0],'small')}<p><strong>Mira</strong> asked for site details on <strong>Four-bedroom home</strong></p><small>Request recorded</small></div><div class="recent-row">${avatar(state.people[1],'small')}<p><strong>Orin</strong> recorded a comparison for <strong>5 W DC-to-AC design</strong></p><small>Authored summary</small></div></section>`);}
  function personas(){const rows=state.people.filter(p=>`${p.name} ${p.character}`.toLocaleLowerCase().includes(personaSearch.toLocaleLowerCase()));return shell(`<header class="page-heading"><div><h1>Personas</h1><p>Continuing identities, not disposable task roles.</p></div>${btn(`${icon('plus')}New persona`,'new-persona',true,'id="new-persona"')}</header><div class="toolbar"><span class="eyebrow muted">${state.people.length} collaborators</span>${searchBox('persona-search','Search personas...',personaSearch)}</div><section class="cards" aria-label="Personas">${rows.map(p=>`<article class="card persona-card"><header class="persona-header">${avatar(p)}<div><h2>${escape(p.name)}</h2><small>${p.note?'Continuing persona':'Local presentation draft'}</small></div></header><p class="persona-description">${escape(p.character)}</p>${badge(p.disposition)}<div class="persona-attention"><div class="eyebrow">Current attention · Illustrative</div><p>${escape(p.attention)}</p><div class="persona-counts"><span><strong>${p.note?1:0}</strong> retained note</span><span><strong>0</strong> acquired tools</span></div></div><a class="text-link" href="#/persona/${escape(p.id)}">Meet ${escape(p.name.split(' ')[0])} ${icon('arrow')}</a></article>`).join('')||'<div class="card empty">No matching personas.</div>'}</section><aside class="notice"><strong>Character can continue while tools and models change.</strong> Open a persona to distinguish long-term learning from attention on a specific run. Initials are intentional placeholders, not generated portraits.</aside>`,'personas','Personas');}
  const detailTabs=[['overview','Overview'],['perspectives','Perspectives'],['outcomes','Work & outcomes'],['people','People & agreements'],['evidence','Artifacts & evidence'],['decisions','Decisions & learning']];
  function tabs(items,selected,scope){return `<div class="tabs" role="tablist" aria-label="${scope==='workspace'?'Fixture views':'Work views'}">${items.map(([id,text])=>`<button id="tab-${id}" role="tab" aria-selected="${id===selected}" tabindex="${id===selected?0:-1}" aria-controls="panel" data-action="tab" data-tab="${id}" data-scope="${scope}" class="${id===selected?'active':''}">${escape(text)}</button>`).join('')}</div>`;}
  function peopleCard(w){return `<section class="card"><h2>Working together</h2>${w.personas.map(id=>state.people.find(p=>p.id===id)).filter(Boolean).map(p=>`<div class="person-row">${avatar(p,'small')}<div><a class="text-link" href="#/persona/${escape(p.id)}">${escape(p.name)}</a><small>${escape(p.disposition)}</small></div></div>`).join('')||'<p class="muted">No participants have accepted this need.</p>'}<p class="notice">Independent reviewer: not assigned. The reviewer must be outside this contributor group under the illustrated policy.</p></section>`;}
  function requestCard(w){if(!w.request)return '<p class="muted">No information request is shown in this fixture. Unknown requirements are not implied to be satisfied.</p>';return w.request==='open'?`<div class="request-card">${badge('One open request','amber')}<h3>Confirm the site and location</h3><p>Share the site location and approximate plot dimensions. Add any known access constraints. “Not known yet” is a valid answer.</p>${btn(`Answer request ${icon('arrow')}`,'answer',true,`data-id="${w.id}" id="answer-detail-${w.id}"`)}</div>`:`<div class="response-panel">${badge('Answered · assessment pending','blue')}<p class="answer-copy">${escape(w.answer)}</p><p class="muted">The request is not resolved. No persona or provider has evaluated this response.</p></div>`;}
  function workDetail(id){const w=state.works.find(w=>w.id===id);if(!w)return notFound();const [label,tone]=status(w);let panel='';
    if(detailTab==='overview')panel=`<div class="detail-grid"><div class="stack"><section class="card"><div class="summary-title"><h2>Where things stand</h2><span class="summary-label">Authored summary</span></div><blockquote>${escape(w.summary)}</blockquote><div class="author-line">${w.personas.length?avatar(state.people[w.id==='circuit'?1:0],'tiny'):''}<span>${w.id==='circuit'?'Orin Reed':w.id==='home'?'Mira Vale':'You · Local draft'} · Sample summary, not a verified result</span></div></section><section class="card"><h2>Your input</h2>${requestCard(w)}</section><section class="card"><h2>The brief</h2><p class="muted">${escape(w.brief)}</p><details><summary>What would count as a useful result?</summary><p>Accepted scope, editable outputs where relevant, appropriate checks, version-bound review and explicit outside limitations. No result has been produced in this preview.</p></details>${w.id==='home'?'<a class="text-link" href="#/workspace/house/3">Explore the evolving-work fixture '+icon('arrow')+'</a>':''}</section></div><aside class="stack">${peopleCard(w)}<section class="card"><h2>Permissions &amp; limits</h2><div class="key-value"><span>External actions</span><strong>Ask for approval</strong></div><div class="key-value"><span>Secrets</span><strong>No access granted</strong></div><div class="key-value"><span>Decision limit</span><strong>100 per run · proposed</strong></div>${btn(`Preview a scoped approval ${icon('arrow')}`,'approval',false,'id="approval-preview"')}<p class="muted" style="margin-top:18px;font-size:11px">Preview only. This work has no credentials or issued grants. An actor limit cannot expand the shared root allowance.</p></section></aside></div>`;
    else if(detailTab==='perspectives')panel=`<div class="cards">${w.personas.map(id=>state.people.find(p=>p.id===id)).filter(Boolean).map(p=>`<section class="card"><header class="persona-header">${avatar(p,'small')}<h2>${escape(p.name)}</h2></header><p class="muted" style="margin-top:18px">${escape(p.attention)}</p><p class="notice">Shared authored perspective · Not a collective commitment or a personality-to-profession assignment.</p></section>`).join('')||'<section class="card">No shared perspectives yet.</section>'}</div><p class="notice">The shared board has no host-computed universal priority. Private interpretations are not displayed.</p>`;
    else if(detailTab==='outcomes')panel='<section class="card"><h2>Accepted scope and ownership</h2><p>No authoritative outcome-coverage projection is available in this fixture.</p><div class="labelled-facts"><div><strong>Continuation responsibility</strong>Not established</div><div><strong>Scope coverage review</strong>Pending</div><div><strong>Accepted owners</strong>Not established by participant selection</div><div><strong>Outcome evidence</strong>No qualifying current evidence</div></div><p class="notice">An empty checklist does not mean 100% complete. Preserve missing owners and conditional assumptions beside the individual agendas.</p></section>';
    else if(detailTab==='people')panel=`<div class="detail-grid">${peopleCard(w)}<section class="card"><h2>Agreements and consent</h2><p class="muted">No exact agreement endorsements, birth or invitation records are shown for this starting fixture.</p><p class="notice">Birth, initialization, membership and commitment acceptance are distinct. A new name does not establish expertise or reviewer independence.</p></section></div>`;
    else if(detailTab==='evidence')panel='<section class="card"><h2>No submission yet</h2><p class="muted">No native files, simulations or verified results are present. There is no artifact to preview or download.</p><div class="labelled-facts"><div><strong>Technical assessment</strong>Not assessed</div><div><strong>User acceptance</strong>Not recorded</div><div><strong>Outside validation</strong>Not established</div><div><strong>Release seal</strong>Not established</div></div></section>';
    else panel=`<section class="card"><h2>Decisions &amp; learning</h2><p>${escape(w.update)}</p><p class="notice">An authored summary is not a shared mind. A stored note is not demonstrated learning transfer. Delivery, acknowledgement and finding disposition remain separate.</p>${w.answer?`<h3>Recorded response</h3><p class="answer-copy">${escape(w.answer)}</p>`:''}</section>`;
    return shell(`<a class="back-link" href="#/work">${icon('back')}All work</a><header class="page-heading detail-heading"><div><h1>${escape(w.title)}</h1><p>${escape(w.environment)} · ${w.personas.length} continuing personas</p></div>${btn(`${icon(w.activity==='paused'?'play':'pause')}${w.activity==='paused'?'Resume preview':'Pause decisions'}`,'pause',false,`data-id="${w.id}" id="pause-${w.id}"`)}</header><section class="status-strip" aria-label="Independent work status"><div class="status-cell"><div class="eyebrow">Activity</div>${badge(label,tone,true)}<small>${w.request==='open'?'One open request':w.request==='answered'?'Answered, not resolved':'Illustrative state'}</small></div><div class="status-cell"><div class="eyebrow">Latest version</div><strong>No submission yet</strong><small>No independent review</small></div><div class="status-cell"><div class="eyebrow">Evidence</div><strong>Not assessed</strong><small>No verified results in this fixture</small></div></section>${tabs(detailTabs,detailTab,'detail')}<div id="panel" role="tabpanel" aria-labelledby="tab-${detailTab}" tabindex="0">${panel}</div>`);
  }
  function personaDetail(id){const p=state.people.find(p=>p.id===id);if(!p)return notFound();return shell(`<a class="back-link" href="#/personas">${icon('back')}All personas</a><header class="persona-header">${avatar(p)}<div><h1>${escape(p.name)}</h1><p class="muted">Continuing identity · Initials, not a generated portrait</p></div></header><div class="profile-grid"><section class="card"><h2>Authored character</h2><p>${escape(p.character)}</p><p class="notice">${escape(p.disposition)} · Descriptive tendencies, not technical qualifications.</p></section><section class="card"><h2>Current attention</h2><p>${escape(p.attention)}</p><p class="notice">OCEAN / VAD: not provided. No trait values or human feelings are inferred from this illustration.</p></section><section class="card"><h2>Retained experience</h2><p>${escape(p.note||'No retained notes.')}</p><p class="notice">${p.note?'One illustrative note. Its later usefulness has not been measured.':'An uninitialized presentation draft is not a real persona birth.'}</p></section><section class="card"><h2>Capabilities &amp; model</h2><div class="key-value"><span>Acquired tools</span><strong>0</strong></div><div class="key-value"><span>Model / provider</span><strong>Not connected</strong></div><div class="key-value"><span>Provenance</span><strong>Authored fixture</strong></div><p class="notice">No private relationship records, credentials or hidden reasoning are displayed.</p></section></div>`,'personas','Personas');}
  function environments(){return shell(`<header class="page-heading"><div><h1>Environments</h1><p>Places for shared work, with explicit resources and access.</p></div></header><div class="cards">${['Willow Studio','Current Lab'].map((name,i)=>`<section class="card"><span class="work-symbol">${icon('layers')}</span><h2 style="margin-top:14px">${name}</h2><p class="muted">3 personas · No acquired tools · No workspace credentials</p><a class="text-link" href="#/work/${i?'circuit':'home'}">Open work ${icon('arrow')}</a></section>`).join('')}</div><p class="notice">Availability in this preview is illustrative. Membership does not grant arbitrary execution or account access.</p>`,'environments','Environments');}
  function learning(){return shell(`<header class="page-heading"><div><h1>Learning</h1><p>Retained notes with sources, applicability and limits.</p></div></header><div class="stack">${state.people.filter(p=>p.note).map(p=>`<article class="card"><header class="persona-header">${avatar(p,'small')}<h2>${escape(p.name)}</h2></header><p style="margin-top:14px">${escape(p.note)}</p><p class="notice">Source: illustrative authored record. Applicability is limited to the stated distinction. No later-use experiment or causal learning benefit is established.</p></article>`).join('')}</div>`,'learning','Learning');}
  function settings(tools=false){return shell(`<header class="page-heading"><div><h1>${tools?'Tools':'Settings'}</h1><p>Local preview only. No connections, tokens or live operations.</p></div></header><div class="stack"><section class="card"><h2>${tools?'No acquired capabilities':'Connections & resources'}</h2><div class="key-value"><span>Providers</span><strong>Not connected</strong></div><div class="key-value"><span>External authority</span><strong>No grants issued</strong></div><div class="key-value"><span>Currency / token usage</span><strong>Unknown, not zero</strong></div><div class="key-value"><span>Network / Advanced</span><strong>No connected node</strong></div>${tools?'<p class="notice">Tool discovery, installation, representative operation and reviewed competence are separate evidence claims. No installation controls are simulated.</p>':'<a class="text-link" href="#/tools">Tools & capability evidence '+icon('arrow')+'</a>'}</section><section class="card"><h2>Design references</h2><p class="muted">The main shell follows the FINAL references. The separate replay follows the WORKSPACE family.</p><a class="text-link" href="#/workspace/house/3">Open evolving-work replay ${icon('arrow')}</a><p class="notice">Tools remains a first-class destination in the production specification. This compact reference shell groups it here to preserve the supplied five-item mobile arrangement.</p></section><section class="card"><h2>Reset this preview</h2><p class="muted">Responses and local drafts exist only in this page’s memory. Reloading also restores the starting fixture.</p>${btn('Reset local changes','reset',false,'id="reset-preview"')}</section></div>`,'settings',tools?'Tools':'Settings');}
  const replayTabs=[['now','Now & next'],['perspectives','Perspectives'],['outcomes','Outcomes'],['people','People & births'],['evidence','Evidence & decisions']];
  function outcomeRows(s){return s.outcomes.map(([title,note,label,owner])=>`<article class="outcome"><div><h3>${escape(title)}</h3><p>${escape(note)}</p><small>Owner: ${escape(owner)}</small></div>${badge(label,label==='Stale'?'red':['Native check recorded'].includes(label)?'':['Pending','Not started'].includes(label)?'blue':'amber')}</article>`).join('');}
  function decisionRows(s){return `<div class="timeline">${s.decisions.map(([title,note])=>`<article class="timeline-item"><h3>${escape(title)}</h3><p>${escape(note)}</p></article>`).join('')}</div>`;}
  function workspace(kind='house',step=3){let s;try{s=D.snapshot(kind,step);}catch{return notFound();}let panel='';
    if(workspaceTab==='now')panel=`<div class="workspace-grid"><div class="stack"><section class="card priority-card"><div class="eyebrow">Current priority · Authored choice</div><h2>${escape(s.priority)}</h2><blockquote>${escape(s.rationale)}</blockquote><p><strong>Owner:</strong> ${escape(s.owner)}</p><p><strong>Expected result:</strong> ${escape(s.expected)}</p></section><section class="card"><h2>What must be accomplished</h2>${outcomeRows(s)}</section></div><aside class="stack"><section class="card"><h2>What changed</h2><p>${escape(s.changed)}</p><p class="muted">Priority and team shape are authored decisions. The runtime preserves and bounds them.</p></section><section class="card"><h2>Needs you / outside evidence</h2><p>${escape(s.outside)}</p></section><section class="card"><h2>Recent decisions</h2>${decisionRows(s)}</section></aside></div>`;
    else if(workspaceTab==='outcomes')panel=`<section class="card"><h2>Outcomes and evidence applicability</h2>${outcomeRows(s)}<p class="notice">Checked among adopted outcomes only. Scope coverage review is pending. No global completion percentage or released result is implied.</p><div class="labelled-facts"><div><strong>Integrated review</strong>Not established</div><div><strong>User acceptance</strong>Not recorded</div><div><strong>Blocking feedback</strong>No complete authoritative projection</div><div><strong>Release seal</strong>Not established</div></div></section>`;
    else if(workspaceTab==='people')panel=`<div class="workspace-grid"><section class="card"><h2>Continuing people</h2>${s.members.map(name=>`<div class="person-row"><span class="avatar small">${escape(name.slice(0,2).toUpperCase())}</span><div><strong>${escape(name)}</strong><small>Illustrative membership · No prescribed profession</small></div></div>`).join('')}<p class="notice">${kind==='house'?(step===1?'No birth in this snapshot.':step===2?'Vale: initialization admitted, invitation offered. Membership and commitment acceptance are pending.':'Vale joined by consent and accepted a bounded first contribution; a new identity does not prove expertise.'):'No birth is needed in this authored trace. Existing peers can agree to contribute.'}</p></section><section class="card"><h2>Agreements & limits</h2><p>Separate birth, membership, agreement endorsement and accepted commitments. No shared biography or averaged group personality.</p><div class="labelled-facts"><div><strong>Root allowance</strong>120 calls including descendants</div><div><strong>Protected closeout</strong>Not supplied in the source fixture</div><div><strong>Independent reviewer</strong>Availability and funding not established</div><div><strong>Iteration baseline</strong>${kind==='house'&&step===3?'Provisional model v4; remaining iteration allowance not supplied':'Not supplied'}</div></div></section></div>`;
    else if(workspaceTab==='perspectives')panel=`<div class="cards">${s.members.map((name,i)=>`<section class="card"><h2>${escape(name)}’s shared perspective</h2><p>${escape(i===0?'Explore alternatives while preserving the accepted purpose.':i===1?'Keep comparison inputs and missing obligations visible.':'Investigate the bounded uncertainty and recheck changed inputs.')}</p><p class="notice">Authored illustrative agenda. Not a profession, personality rule or compulsory ranking. Accepted ownership is shown separately.</p></section>`).join('')}</div>`;
    else panel=`<section class="card"><h2>Evidence &amp; decisions</h2>${decisionRows(s)}<p class="notice">All records here are fictional snapshots. “Native check recorded” names an illustrative receipt, not actual artifact bytes or a technical pass. No CAD, simulation, release or learning evaluation ran.</p><div class="labelled-facts"><div><strong>Historical evidence</strong>Retained for its original inputs</div><div><strong>Changed inputs</strong>Old assessments cannot qualify new versions</div><div><strong>External requirements</strong>${escape(s.outside)}</div><div><strong>Reproduction</strong>Unavailable: this fixture has no native artifacts</div></div></section>`;
    return `<header class="workspace-header">${brand()}<small>Work shaped by people. Organization shaped by experience.</small><span class="badge">Design prototype</span></header><div class="fixture-warning">Illustrative fixtures only. No personas, providers, engineering simulations, or external actions are running.</div><main id="main" class="workspace-main" tabindex="-1"><div class="workspace-links"><a href="#/work">${icon('back')} All work</a><a href="#/work/home">Application detail</a></div><div class="replay-controls"><label for="scenario">Need</label><select id="scenario">${D.scenarioKeys.map(key=>`<option value="${key}" ${key===kind?'selected':''}>${escape(D.snapshot(key,1).need)}</option>`).join('')}</select><span class="muted">Replay</span><div class="replay-steps" role="group" aria-label="Authored fixture snapshot">${['Starting work','New evidence','Team response'].map((label,i)=>`<a class="btn ${step===i+1?'active':''}" href="#/workspace/${kind}/${i+1}" ${step===i+1?'aria-current="step"':''}>${i+1} · ${label}</a>`).join('')}</div></div><header class="workspace-title"><div><div class="eyebrow">Evolving work mandate · Fixture snapshot ${step}</div><h1>${escape(s.title)}</h1><p>${escape(s.description)}</p><span class="pill">${s.members.length} continuing ${s.members.length===1?'persona':'personas'}</span> <span class="pill">No prescribed professions</span></div><aside class="card budget"><div class="eyebrow">Root allowance</div><strong>${s.calls} / ${s.allowance} calls</strong><small>All descendants share this allowance</small><progress value="${s.calls}" max="${s.allowance}" aria-label="Illustrative root calls used">${s.calls} / ${s.allowance}</progress></aside></header>${tabs(replayTabs,workspaceTab,'workspace')}<div id="panel" role="tabpanel" aria-labelledby="tab-${workspaceTab}" tabindex="0">${panel}</div><footer class="workspace-foot">Same renderer, different persona-authored work records. Budgets are illustrative model-call allowances—not dollar caps. Evidence labels apply only within these fictional snapshots. Protected closeout allocation is not supplied; it is not assumed zero.</footer></main>`;
  }
  function notFound(){return shell('<section class="card empty"><h1>Page not found</h1><p class="muted">This design preview contains only the documented fixtures.</p><a class="text-link" href="#/work">Return to Work '+icon('arrow')+'</a></section>');}
  function parts(){return location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);}
  function render(preserve=false){const focused=preserve&&document.activeElement;const id=focused&&focused.id;const start=focused&&focused.selectionStart;const end=focused&&focused.selectionEnd;const p=parts();let html;switch(p[0]||'work'){case'work':html=p[1]?workDetail(p[1]):workList();break;case'personas':html=personas();break;case'persona':html=personaDetail(p[1]);break;case'environments':html=environments();break;case'learning':html=learning();break;case'settings':html=settings();break;case'tools':html=settings(true);break;case'workspace':html=workspace(p[1],Number(p[2]||3));break;default:html=notFound();}app.innerHTML=html;document.title=`${document.querySelector('h1')?.textContent||'Work'} · AI Personas design preview`;if(id){const node=document.getElementById(id);if(node){node.focus({preventScroll:true});if(typeof start==='number'&&typeof node.setSelectionRange==='function')node.setSelectionRange(start,end);}}}
  function announce(text){document.getElementById('announcement').textContent=text;}
  function openDialog(kind,id){opener=document.activeElement;openerId=opener?.id;const work=state.works.find(w=>w.id===id);let title='',body='',submit='',eyebrow='Design preview';
    if(kind==='answer'&&work){title='Confirm the site and location';eyebrow=`Mira Vale · ${work.title}`;body='<p>Share the site location and approximate plot dimensions. Add any known access constraints. “Not known yet” is a valid answer.</p><aside class="notice">This is a request for information, not permission to act on an external account.</aside><label class="field" for="answer">Your answer<textarea id="answer" name="answer" maxlength="5000" required autofocus aria-describedby="answer-help" placeholder="Location, plot dimensions, access constraints —or what is not known yet."></textarea></label><p class="hint muted" id="answer-help">Unknown details stay unknown. The persona will evaluate the response before resolving the request.</p><p class="preview-hint muted">Design preview: the response is stored only in this page’s memory.</p>';submit='Record response';}
    else if(kind==='new-work'){title='New work';body='<p>Describe a need. This records a local draft; it does not start personas or spend resources.</p><label class="field" for="work-title">Title<input id="work-title" name="title" maxlength="80" required autofocus placeholder="A short, memorable name"></label><label class="field" for="work-brief">Your need<textarea id="work-brief" name="brief" maxlength="5000" required placeholder="What would you like to accomplish?"></textarea></label><p class="notice">No participant is silently selected or committed. The draft remains awaiting acceptance.</p>';submit='Record draft';}
    else if(kind==='new-persona'){title='New persona preview';body='<p>Create a local presentation draft. A real birth would require bounded admission, initialization, separate membership consent and an accepted commitment.</p><label class="field" for="persona-name">Name<input id="persona-name" name="name" required maxlength="80" autofocus placeholder="A continuing identity"></label><p class="notice">No model is called, portrait generated, profession assigned or knowledge invented.</p>';submit='Create local draft';}
    else if(kind==='approval'){title='Preview a scoped approval';body='<p>A real approval must identify the principal, exact account/resource, action and payload, scope, expiry, and revocation terms.</p><div class="key-value"><span>Resource / payload</span><strong>Not supplied</strong></div><div class="key-value"><span>Credential handle</span><strong>None</strong></div><div class="key-value"><span>Authority</span><strong>Not granted</strong></div><p class="notice">This is an informational preview. No approve control is offered because there is no concrete external action or implemented grant endpoint.</p>';}
    else if(kind==='reset'){title='Reset local preview?';body='<p>This removes only your in-memory answers and local drafts, restoring the original fictional records. It has no effect on a node, account or repository.</p>';submit='Reset preview';}
    else return;
    dialog.innerHTML=`<form id="dialog-form" data-kind="${kind}" data-id="${escape(id||'')}"><header class="dialog-header"><div><div class="eyebrow">${escape(eyebrow)}</div><h2 id="dialog-title">${title}</h2></div><button type="button" class="icon-btn" data-close aria-label="Close dialog">${icon('close')}</button></header><div class="dialog-body">${body}<p id="form-error" class="error" role="alert"></p></div><footer class="dialog-footer"><button type="button" class="btn" data-close>${submit?'Cancel':'Close preview'}</button>${submit?`<button class="btn primary" type="submit">${submit}</button>`:''}</footer></form>`;
    document.body.classList.add('modal-open');dialog.showModal();
  }
  dialog.addEventListener('close',()=>{if(dialog.open)return;document.body.classList.remove('modal-open');const old=opener,oldId=openerId;dialog.innerHTML='';requestAnimationFrame(()=>{const target=oldId&&document.getElementById(oldId);(target||old?.isConnected&&old||document.getElementById('main'))?.focus({preventScroll:true});});});
  dialog.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const controls=[...dialog.querySelectorAll('button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),a[href],[tabindex="0"]')].filter(el=>el.getClientRects().length);if(!controls.length){event.preventDefault();return;}const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
  dialog.addEventListener('click',event=>{if(event.target.closest('[data-close]'))dialog.close();else if(event.target===dialog){const box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close();}});
  dialog.addEventListener('submit',event=>{event.preventDefault();const form=event.target;const fields=new FormData(form);try{let message='';if(form.dataset.kind==='answer'){state=D.transition(state,{type:'answer',id:form.dataset.id,text:fields.get('answer')});message='Response recorded in this page only. The request is answered, not resolved.';}else if(form.dataset.kind==='new-work'){state=D.transition(state,{type:'work',title:fields.get('title'),brief:fields.get('brief')});message='Local draft recorded. Awaiting acceptance; no persona was started.';}else if(form.dataset.kind==='new-persona'){state=D.transition(state,{type:'persona',name:fields.get('name')});message='Local presentation draft created. No real persona was born.';}else if(form.dataset.kind==='reset'){state=D.initialState();filter='all';workSearch='';personaSearch='';message='Local preview reset.';}dialog.close();render();announce(message);}catch(error){document.getElementById('form-error').textContent=error.message;}});
  app.addEventListener('click',event=>{const node=event.target.closest('[data-action]');if(!node)return;const action=node.dataset.action;if(action==='filter'){filter=node.dataset.filter;render();document.getElementById(`filter-${filter}`)?.focus({preventScroll:true});announce(`${D.filterWorks(state,filter,workSearch).length} matching work items.`);}else if(action==='tab'){if(node.dataset.scope==='workspace')workspaceTab=node.dataset.tab;else detailTab=node.dataset.tab;render();document.getElementById(`tab-${node.dataset.tab}`)?.focus({preventScroll:true});}else if(action==='pause'){state=D.transition(state,{type:'pause',id:node.dataset.id});render();document.getElementById(`pause-${node.dataset.id}`)?.focus();announce('Preview activity changed only. No running jobs or real decisions were controlled.');}else openDialog(action,node.dataset.id);});
  app.addEventListener('input',event=>{if(event.target.id==='work-search'){workSearch=event.target.value;render(true);announce(`${D.filterWorks(state,filter,workSearch).length} matching work items.`);}else if(event.target.id==='persona-search'){personaSearch=event.target.value;render(true);}});
  app.addEventListener('change',event=>{if(event.target.id==='scenario')location.hash=`/workspace/${event.target.value}/1`;});
  app.addEventListener('keydown',event=>{if(event.target.getAttribute('role')!=='tab')return;const keys=['ArrowLeft','ArrowRight','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();const buttons=[...event.target.parentElement.querySelectorAll('[role="tab"]')];const current=buttons.indexOf(event.target);const target=event.key==='Home'?0:event.key==='End'?buttons.length-1:(current+(event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[target].click();document.querySelector('[role="tab"][aria-selected="true"]')?.scrollIntoView({block:'nearest',inline:'nearest'});});
  window.addEventListener('hashchange',()=>{if(dialog.open)dialog.close();detailTab='overview';workspaceTab='now';render();window.scrollTo(0,0);document.getElementById('main')?.focus({preventScroll:true});});
  render();
})();
