import { ErasePayload, AllowanceSummary } from './Operator';
import type { ComponentChildren } from 'preact';
import { lazy, Suspense } from 'preact/compat';
import { useEffect, useRef, useState } from 'preact/hooks';
import { data, label, request, type Entity, type Action, type Page } from './api';
import { useRecords, useResource } from './hooks';
import { Facts, Portrait, Pagination, Status, type Act } from './main';
import { assessmentFacts, isRecordID, recordIDs, text } from './workspace';
import Dialog from './Dialog';
const Upload = lazy(() => import('./Upload'));
const Pick = lazy(() => import('./Create').then(m => ({ default: m.Pick })));
function Expand({ title, children }: { title: string; children: () => ComponentChildren }) { const [open, setOpen] = useState(false); return <section class="expand"><button class="expand-title" aria-expanded={open} onClick={() => setOpen(!open)}>{title} {open ? '−' : '+'}</button>{open && children()}</section>; }
export default function Detail({ id, open, artifact, close, act }: { id: string; open: (id: string) => void; artifact: (id: string) => void; close: () => void; act: Act }) {
  const { value: r, error } = useResource<Entity>('/records/' + id, e => e.entity === id || e.data?.scope === id);
  const [tab, setTab] = useState(''), [failure, setFailure] = useState(''), [review, setReview] = useState(false), [reviewers, setReviewers] = useState<string[]>([]), [reviewBusy, setReviewBusy] = useState(false);
  const d = r ? data(r) : {};
  const tabs = r?.kind === 'work' ? ['Activity', 'Submissions', 'Assessments', 'Requests'] : r?.kind === 'persona' ? ['Work', 'Learning', 'Tools', 'Perspectives', 'Messages', 'History'] : r?.kind === 'environment' ? ['Work', 'Learning', 'Messages'] : r?.kind === 'run' ? ['Actions', 'Model calls'] : r?.kind === 'request' ? ['Responses'] : [];
  const current = tab || tabs[0];
  const actSafe: Act = async (...args) => { setFailure(''); try { return await act(...args); } catch (e) { setFailure((e as Error).message); throw e; } };
  return <Dialog label="Record details" close={close} drawer><div class="drawer"><header><div><p class="eyebrow">{r?.kind || 'Details'}</p><h2>{r ? label(r) : 'Loading…'}</h2></div><button onClick={close}>Close details</button></header><div class="drawer-body">
    {(error || failure) && <p role="alert">{error || failure}</p>}{r && <>
      <Facts r={r}/><p class="long-text">{[d.character, d.description, d.brief, d.content, d.instructions, d.summary, d.findings, d.text, d.purpose].map(v => text(v)).find(Boolean)}</p>
      {text(d.note) && <p class="notice">{d.note}</p>}{text(d.error) && <p role="alert">{d.error}</p>}
      {['persona', 'environment'].includes(r.kind) && <><Portrait id={d.portrait || d.image} name={label(r)}/>{isRecordID(d.portrait || d.image) && <button class="text-button" onClick={() => artifact(d.portrait || d.image)}>Inspect original image</button>}</>}
      {r.kind === 'persona' && <><p>Chosen model: {text(d.provider, 'not recorded')} / {text(d.model, 'not recorded')}</p>
        <p class="notice">Preference, demonstrated competence and accepted responsibility are different. No profession is inferred from character or traits.</p>
        <Expand title="Character and carried context">{() => <><p>Unauthored traits remain absent. State changes are authored, not automatic rewards.</p><pre>{JSON.stringify({ ocean: d.ocean, vad: d.vad, interests: d.interests, attributes: d.attributes }, null, 2)}</pre><p class="long-text">{text(d.reason)}</p><p class="long-text">{text(d.context, 'No compacted account authored yet.')}</p>{recordIDs(d.selected).map(ref => <button key={ref} class="record-link" onClick={() => open(ref)}>Selected record {ref.slice(0, 8)}</button>)}</>}</Expand></>}
      {['persona', 'environment'].includes(r.kind) && <Expand title="Send a message">{() => <MessageForm to={id} act={actSafe}/>}</Expand>}
      {r.kind === 'run' && <><div class="button-row"><button disabled={['queued', 'running'].includes(d.status)} onClick={() => void actSafe('run.resume', { id }).catch(() => {})}>Resume</button><button class="secondary" onClick={() => void actSafe('run.pause', { id }).catch(() => {})}>Pause decisions</button><button class="secondary" onClick={() => void actSafe('run.cancel', { id }).catch(() => {})}>Cancel work</button></div><p class="micro">Pause stops decisions; existing jobs may continue. Cancel cannot undo completed external effects.</p></>}
      {r.kind === 'request' && <><h3>Evidence requested</h3><p class="long-text">{text(d.evidence_required)}</p><Attachments ids={d.artifacts} artifact={artifact}/><p class="notice">A response returns to the owner; acknowledgement does not establish disposition or verified repair.</p><Respond id={id} act={actSafe}/></>}
      {r.kind === 'response' && <><Attachments ids={d.artifacts} artifact={artifact}/>{isRecordID(d.request) && <button onClick={() => open(d.request)}>Open request</button>}</>}
      {r.kind === 'submission' && <><Attachments ids={d.artifacts} artifact={artifact}/>{recordIDs(d.documents).map(ref => <button key={ref} class="record-link" onClick={() => open(ref)}>Open retained document {ref.slice(0, 8)}</button>)}
        <button class="secondary" onClick={() => setReview(!review)}>Request independent review</button>
        {review && <form onSubmit={async e => { e.preventDefault(); if (reviewBusy) return; setReviewBusy(true); try { await actSafe('review.start', { submission: id, persona: reviewers[0], instructions: String(new FormData(e.currentTarget).get('instructions')) }); setReview(false); } catch { /* actSafe displays the retained failure. */ } finally { setReviewBusy(false); } }}>
          <p class="notice">The reviewer needs accepted participation, responsibility, and funding. The node checks the exact evidence and current scope.</p>
          <Suspense fallback={<p>Loading personas…</p>}><Pick kind="persona" value={reviewers} onChange={setReviewers}/></Suspense><label>Reviewer instructions<textarea name="instructions" required rows={4}/></label><button disabled={!reviewers.length || reviewBusy}>{reviewBusy ? 'Requesting…' : 'Start review'}</button></form>}
        <Records key={'finding' + id} kind="finding" scope={r.scope} filter={x => data(x).submission === id} open={open}/></>}
      {['finding', 'assessment'].includes(r.kind) && <><p>Historical verdict: <Status value={assessmentFacts(r).verdict}/></p><p>Reported applicability: <Status value={assessmentFacts(r).applicability}/></p><p class="notice">{assessmentFacts(r).note}</p>
        {isRecordID(d.submission) && <p>Exact submission <button class="text-button" onClick={() => open(d.submission)}>{d.submission.slice(0, 8)}</button></p>}
        <p>{recordIDs(d.checks).length} referenced checks. Command completion alone is not technical validation.</p>{recordIDs(d.checks).map(ref => <Expand key={ref} title={'Check ' + ref.slice(0, 8)}>{() => <ActionRecord id={ref} act={actSafe}/>}</Expand>)}</>}
      {r.kind === 'call' && <><p>{text(d.actual_model, 'Actual model not recorded')} · {text(d.status)}</p><p>{d.usage?.known ? `${d.usage.input} input · ${d.usage.cached} cached · ${d.usage.output} output tokens` : 'Usage unknown'}</p><p class="micro">Recorded usage is not a currency budget or a host-wide spend measure.</p><p>{d.context_bytes?.toLocaleString()} context bytes · {d.images?.length || 0} selected image inputs</p>
        <p class="notice">Provider archives may contain confidential task material or provider-internal data. They are diagnostics, not a public persona thought stream.</p>
        <Expand title="Protected provider diagnostics">{() => <>{['request.json', 'input.json', 'response.json', 'provider.jsonl'].map(part => <a key={part} class="record-link" href={'/api/calls/' + id + '/' + part} target="_blank" rel="noreferrer">Inspect {part}</a>)}</>}</Expand></>}
      {r.kind === 'resource_root' && <AllowanceSummary id={id}/>}
      {['document', 'artifact', 'fragment', 'perspective', 'message'].includes(r.kind) && <ErasePayload record={r} act={actSafe}/>}
      {r.kind === 'artifact' && <button onClick={() => artifact(id)}>Open artifact viewer</button>}
      {tabs.length > 0 && <><nav class="tabs" aria-label="Detail sections">{tabs.map(t => <button key={t} class={current === t ? 'active' : ''} onClick={() => setTab(t)}>{t}</button>)}</nav>
        {current === 'Actions' || current === 'History' ? <Actions key={current + id} owner={r.kind === 'persona' ? id : ''} run={r.kind === 'run' ? id : ''} act={actSafe}/>
          : <Records key={current + id} kind={({ Activity: 'run', Work: r.kind === 'persona' ? 'run' : 'work', Learning: 'fragment,document', Tools: 'tool,capability', Perspectives: 'perspective', Messages: 'message', 'Model calls': 'call', Submissions: 'submission', Assessments: 'finding,assessment', Requests: 'request', Responses: 'response' } as Record<string, string>)[current]} scope={r.kind === 'persona' ? '' : id} owner={r.kind === 'persona' ? id : ''} open={open}/>}
      </>}
      <Expand title="Exact record fields">{() => <pre>{JSON.stringify(r.data, null, 2)}</pre>}</Expand><Expand title="Preserved revisions">{() => <Revisions id={id}/>}</Expand><p class="micro">{id}</p>
    </>}</div></div></Dialog>;
}
function Attachments({ ids, artifact }: { ids?: string[]; artifact: (id: string) => void }) { return <div class="attachment-list">{recordIDs(ids).map(id => <button class="secondary" key={id} onClick={() => artifact(id)}>Open attachment {id.slice(0, 8)}</button>)}</div>; }
function MessageForm({ to, act }: { to: string; act: Act }) { const [busy, setBusy] = useState(false), [sent, setSent] = useState(''); return <form onSubmit={async e => { e.preventDefault(); if (busy) return; const form = e.currentTarget; setBusy(true); try { await act('message.send', { to, text: String(new FormData(form).get('text')) }); form.reset(); setSent('Message sent. A message does not assign responsibility.'); } catch { /* Parent displays the failure. */ } finally { setBusy(false); } }}><label>Message<textarea name="text" required rows={3}/></label><button disabled={busy}>Send message</button>{sent && <p role="status">{sent}</p>}</form>; }
function Respond({ id, act }: { id: string; act: Act }) { const [files, setFiles] = useState<{ id: string; name: string }[]>([]), [busy, setBusy] = useState(false), [sent, setSent] = useState(''); return <form onSubmit={async e => { e.preventDefault(); if (busy) return; const form = e.currentTarget; setBusy(true); try { await act('request.respond', { request: id, text: String(new FormData(form).get('text')), artifacts: files.map(f => f.id) }); form.reset(); setFiles([]); setSent('Response delivered to the owner; disposition is not established.'); } catch { /* Parent displays the failure. */ } finally { setBusy(false); } }}><label>Your response<textarea name="text" rows={4} required placeholder="Facts, observations, a decision, or measurements…"/></label><Suspense fallback={<p>Loading attachment control…</p>}><Upload onFile={(ref, name) => setFiles(fs => [...fs, { id: ref, name }])}/></Suspense>{files.map(f => <p key={f.id}>{f.name} <button type="button" class="quiet" onClick={() => setFiles(files.filter(x => x.id !== f.id))}>Remove</button></p>)}<button disabled={busy}>{busy ? 'Sending…' : 'Send response'}</button>{sent && <p role="status">{sent}</p>}</form>; }
function Records({ kind, scope = '', owner = '', open, filter }: { kind: string; scope?: string; owner?: string; open: (id: string) => void; filter?: (r: Entity) => boolean }) { const [cursors, setCursors] = useState([0]); const { value: page, error } = useRecords(kind, scope, owner, '', cursors.at(-1)); const rows = page?.items.filter(filter || (() => true)); return <section>{error && <p role="alert">{error}</p>}{rows?.map(r => <button key={r.id} class="record-link" onClick={() => open(r.id)}><span>{label(r)}<small>{r.created} · {r.id.slice(0, 8)}</small></span><Status value={text(data(r).status) || text(data(r).verdict) || r.kind}/></button>)}{rows?.length === 0 && !error && <p>No matching records on this page.</p>}<Pagination previous={cursors.length > 1} next={page?.next} onPrevious={() => setCursors(cursors.slice(0, -1))} onNext={() => { if (page?.next != null) setCursors([...cursors, page.next]); }}/></section>; }
function Actions({ owner, run, act }: { owner: string; run: string; act: Act }) { const [cursors, setCursors] = useState([0]); const { value: page, error } = useResource<Page<Action>>('/actions?' + new URLSearchParams({ owner, scope: run, after: String(cursors.at(-1)), limit: '20' }), e => e.kind === 'action' && (run ? e.data?.run === run : e.data?.actor === owner)); return <section>{error && <p role="alert">{error}</p>}{page?.items.map(a => <Expand key={a.request.id} title={a.request.kind + ' · ' + a.state}>{() => <ActionBody a={a} act={act}/>}</Expand>)}<Pagination previous={cursors.length > 1} next={page?.next} onPrevious={() => setCursors(cursors.slice(0, -1))} onNext={() => { if (page?.next != null) setCursors([...cursors, page.next]); }}/></section>; }
function ActionRecord({ id, act }: { id: string; act: Act }) { const { value, error } = useResource<Action>('/actions/' + id, e => e.entity === id); return error ? <p role="alert">{error}</p> : value ? <ActionBody a={value} act={act}/> : <p>Loading check…</p>; }
function ActionBody({ a, act }: { a: Action; act: Act }) { const [output, setOutput] = useState(false); return <>{a.request.kind === 'model.choose' && <p>{a.request.source === 'api' ? 'Operator model choice' : 'Persona model choice'}</p>}<pre>{JSON.stringify(a.request.args, null, 2)}</pre>{a.error && <p role="alert">{a.error}</p>}<pre>{JSON.stringify(a.result, null, 2)}</pre>{a.request.kind === 'exec' && <><p class="notice">{a.state === 'running' ? 'Tool execution is pending. Launch is not completion.' : 'This receipt records execution, not engineering correctness.'}</p><button onClick={() => setOutput(!output)}>{output ? 'Close output' : 'Follow output'}</button>{a.state === 'running' && <button class="secondary" onClick={() => void act('job.cancel', { id: a.request.id }).catch(() => {})}>Cancel job</button>}{output && <Output id={a.request.id} terminal={a.state !== 'running'}/>}</>}</>; }
function Output({ id, terminal }: { id: string; terminal: boolean }) { const [body, setBody] = useState(''), [done, setDone] = useState(false), [error, setError] = useState(''); const offset = useRef(0); useEffect(() => { const c = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined; offset.current = 0; setBody(''); setError(''); const load = async () => { try { const r = await request<any>(`/actions/${id}/output?offset=${offset.current}`, { signal: c.signal }); if (c.signal.aborted) return; offset.current = r.offset; setBody(t => (t + r.text).slice(-65536)); setDone(!!r.receipt?.done || terminal); if (!r.receipt?.done && !terminal) timer = setTimeout(load, 350); } catch (e) { if (!c.signal.aborted) setError((e as Error).message); } }; void load(); return () => { c.abort(); clearTimeout(timer); }; }, [id, terminal]); return <section>{error && <p role="alert">{error}</p>}<pre class="output">{body || 'Waiting for output…'}</pre><small>{done ? 'Execution has a terminal disposition; inspect the receipt.' : 'Following output. Closing this view does not cancel work.'} Showing at most the latest 65,536 characters.</small></section>; }
function Revisions({ id }: { id: string }) { const [cursors, setCursors] = useState([0]); const { value: page, error } = useResource<Page<Entity>>(`/records/${id}/revisions?after=${cursors.at(-1)}&limit=10`, e => e.entity === id); return <>{error && <p role="alert">{error}</p>}{page?.items.map((r, i) => <Expand key={r.revision + ':' + i} title={'Revision ' + r.revision + ' · ' + r.updated}>{() => <pre>{JSON.stringify(r.data, null, 2)}</pre>}</Expand>)}<Pagination previous={cursors.length > 1} next={page?.next} onPrevious={() => setCursors(cursors.slice(0, -1))} onNext={() => { if (page?.next != null) setCursors([...cursors, page.next]); }}/></>; }
