import type { ComponentChildren } from 'preact';
import { lazy, Suspense } from 'preact/compat';
import { useEffect, useRef, useState } from 'preact/hooks';
import { data,label,fileURL,request,type Entity,type Action,type Page } from './api';
import { useRecords,useResource } from './hooks';
import { Facts,Portrait,Pagination,Status,type Act } from './main';
const Upload=lazy(()=>import('./Upload'));
const Pick=lazy(()=>import('./Create').then(m=>({default:m.Pick})));
function Expand({title,children}:{title:string;children:()=>ComponentChildren}) {const [open,setOpen]=useState(false);return <section class="expand"><button class="expand-title" aria-expanded={open} onClick={()=>setOpen(!open)}>{title} {open?'−':'+'}</button>{open && children()}</section>;}
export default function Detail({id,open,artifact,close,act}:{id:string;open:(id:string)=>void;artifact:(id:string)=>void;close:()=>void;act:Act}) {
  const {value:r,error}=useResource<Entity>('/records/'+id,e=>e.entity===id || e.data?.scope===id);
  const [tab,setTab]=useState('');const [failure,setFailure]=useState('');const [review,setReview]=useState(false);const [reviewers,setReviewers]=useState<string[]>([]);
  const d=r?data(r):{};
  const tabs = r?.kind==='work' ? ['Activity','Submissions','Assessments','Requests'] : r?.kind==='persona' ? ['Work','Learning','Tools','Messages','History'] : r?.kind==='environment' ? ['Work','Learning','Messages'] : r?.kind==='run' ? ['Actions','Model calls'] : r?.kind==='request' ? ['Responses'] : [];
  const current=tab || tabs[0];
  const actSafe:Act=async(...args)=>{setFailure('');try{return await act(...args);}catch(e){setFailure((e as Error).message);throw e;}};
  return <div class="drawer" role="dialog" aria-modal="true" aria-label="Record details"><header><div><p class="eyebrow">{r?.kind || 'Details'}</p><h2>{r?label(r):'Loading…'}</h2></div><button onClick={close}>Close details</button></header><div class="drawer-body">{(error||failure)&&<p role="alert">{error||failure}</p>}{r && <>
    <Facts r={r}/><p class="long-text">{d.character || d.description || d.brief || d.content || d.instructions || d.summary || d.findings || d.text || d.purpose}</p>{d.note && <p class="notice">{d.note}</p>}{d.error&&<p role="alert">{d.error}</p>}
    {['persona','environment'].includes(r.kind)&&<Portrait id={d.portrait||d.image} name={label(r)}/>}
    {r.kind==='persona'&&<><p>Chosen model: {d.provider} / {d.model}</p><Expand title="Character and carried context">{()=> <><p>Unauthored traits remain absent. Dispositions and affect evolve through the persona’s explanations.</p><pre>{JSON.stringify({ocean:d.ocean,vad:d.vad,attributes:d.attributes},null,2)}</pre><p class="long-text">{d.reason}</p><p class="long-text">{d.context || 'No compacted account authored yet.'}</p>{d.selected?.map((id:string)=><button key={id} class="record-link" onClick={()=>open(id)}>Selected record {id.slice(0,8)}</button>)}</>}</Expand></>}
    {['persona','environment'].includes(r.kind)&&<Expand title="Send a message">{()=> <form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;await actSafe('message.send',{to:r.id,text:new FormData(form).get('text')});form.reset();}}><label>Message<textarea name="text" required rows={3}/></label><button>Send message</button></form>}</Expand>}
    {r.kind==='run'&&<div class="button-row"><button disabled={['queued','running'].includes(d.status)} onClick={()=>actSafe('run.resume',{id}).catch(()=>{})}>Resume</button><button class="secondary" onClick={()=>actSafe('run.pause',{id}).catch(()=>{})}>Pause decisions</button><button class="secondary" onClick={()=>actSafe('run.cancel',{id}).catch(()=>{})}>Cancel work</button></div>}
    {r.kind==='request'&&<><h3>Evidence requested</h3><p class="long-text">{d.evidence_required}</p><Attachments ids={d.artifacts} artifact={artifact}/><p class="notice">This request belongs to a persona. A response returns to them for assessment; it does not automatically close the request.</p><Respond id={id} act={actSafe}/></>}
    {r.kind==='response'&&<><Attachments ids={d.artifacts} artifact={artifact}/><button onClick={()=>open(d.request)}>Open request</button></>}
    {r.kind==='submission'&&<><Attachments ids={d.artifacts} artifact={artifact}/>{d.documents?.map((id:string)=><button key={id} class="record-link" onClick={()=>open(id)}>Open retained document {id.slice(0,8)}</button>)}<button class="secondary" onClick={()=>setReview(!review)}>Request independent review</button>{review&&<form onSubmit={async e=>{e.preventDefault();await actSafe('review.start',{submission:id,persona:reviewers[0],instructions:new FormData(e.currentTarget).get('instructions')});setReview(false);}}><Suspense fallback={<p>Loading personas…</p>}><Pick kind="persona" value={reviewers} onChange={setReviewers}/></Suspense><label>Reviewer instructions<textarea name="instructions" required rows={4}/></label><button disabled={!reviewers.length}>Start review</button></form>}<Records key={'finding'+id} kind="finding" scope={r.scope} filter={x=>data(x).submission===id} open={open}/></>}
    {r.kind==='finding'&&<><Status value={d.verdict}/><p>Assessment of exact submission <button class="text-button" onClick={()=>open(d.submission)}>{d.submission.slice(0,8)}</button></p><p>{d.checks?.length || 0} preserved checks. The reviewer’s findings explain their significance.</p>{d.checks?.map((a:string)=><Expand key={a} title={'Check '+a.slice(0,8)}>{()=> <ActionRecord id={a} act={actSafe}/>}</Expand>)}</>}
    {r.kind==='call'&&<><p>{d.actual_model || 'Actual model not recorded'} · {d.status}</p><p>{d.usage?.known?`${d.usage.input} input · ${d.usage.cached} cached · ${d.usage.output} output tokens`:'Usage unknown'}</p><p class="micro">Usage observed through this application. Host-wide usage is not measured.</p>{d.error&&<p role="alert">{d.error}</p>}<p>{d.context_bytes?.toLocaleString()} recorded context bytes · {d.images?.length||0} selected image inputs</p>{['request.json','input.json','response.json','provider.jsonl'].map(part=><a key={part} class="record-link" href={'/api/calls/'+id+'/'+part} target="_blank" rel="noreferrer">Inspect {part}</a>)}</>}
    {r.kind==='artifact'&&<button onClick={()=>artifact(id)}>Open artifact viewer</button>}
    {tabs.length>0&&<><nav class="tabs" aria-label="Detail sections">{tabs.map(t=><button key={t} class={current===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
      {current==='Actions'||current==='History'?<Actions key={current+id} owner={r.kind==='persona'?id:''} run={r.kind==='run'?id:''} act={actSafe}/>:<Records key={current+id} kind={({'Activity':'run','Work':r.kind==='persona'?'run':'work','Learning':'document','Tools':'tool','Messages':'message','Model calls':'call','Submissions':'submission','Assessments':'finding','Requests':'request','Responses':'response'} as Record<string,string>)[current]} scope={r.kind==='persona'?'':id} owner={r.kind==='persona'?id:''} open={open}/>}
    </>}
    <Expand title="Preserved revisions">{()=> <Revisions id={id}/>}</Expand><p class="micro">{id}</p>
  </>}</div></div>;
}
function Attachments({ids,artifact}:{ids?:string[];artifact:(id:string)=>void}){return <div class="attachment-list">{ids?.map(id=><button class="secondary" key={id} onClick={()=>artifact(id)}>Open attachment {id.slice(0,8)}</button>)}</div>;}
function Respond({id,act}:{id:string;act:Act}){const [files,setFiles]=useState<{id:string;name:string}[]>([]);const [busy,setBusy]=useState(false);const [sent,setSent]=useState('');return <form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);try{await act('request.respond',{request:id,text:String(new FormData(form).get('text')),artifacts:files.map(f=>f.id)});form.reset();setFiles([]);setSent('Response delivered to the owner.');}finally{setBusy(false);}}}><label>Your response<textarea name="text" rows={4} required placeholder="Facts, observations, a decision, or measurements…"/></label><Suspense fallback={<p>Loading attachment control…</p>}><Upload onFile={(id,name)=>setFiles(fs=>[...fs,{id,name}])}/></Suspense>{files.map(f=><p key={f.id}>{f.name} <button type="button" class="quiet" onClick={()=>setFiles(files.filter(x=>x.id!==f.id))}>Remove</button></p>)}<button disabled={busy}>{busy?'Sending…':'Send response'}</button>{sent&&<p role="status">{sent}</p>}</form>;}
function Records({kind,scope='',owner='',open,filter}:{kind:string;scope?:string;owner?:string;open:(id:string)=>void;filter?:(r:Entity)=>boolean}){const [cursors,setCursors]=useState([0]);const {value:page,error}=useRecords(kind,scope,owner,'',cursors.at(-1));return <section>{error&&<p role="alert">{error}</p>}{page?.items.filter(filter||(()=>true)).map(r=><button key={r.id} class="record-link" onClick={()=>open(r.id)}><span>{label(r)}<small>{r.created} · {r.id.slice(0,8)}</small></span><Status value={data(r).status || data(r).verdict || r.kind}/></button>)}{page?.items.length===0&&<p>No records yet.</p>}<Pagination previous={cursors.length>1} next={page?.next} onPrevious={()=>setCursors(cursors.slice(0,-1))} onNext={()=>page?.next&&setCursors([...cursors,page.next])}/></section>;}
function Actions({owner,run,act}:{owner:string;run:string;act:Act}){const [cursors,setCursors]=useState([0]);const {value:page,error}=useResource<Page<Action>>('/actions?'+new URLSearchParams({owner,scope:run,after:String(cursors.at(-1)),limit:'20'}),e=>e.kind==='action' && (e.data?.run===run||e.data?.actor===owner));return <section>{error&&<p role="alert">{error}</p>}{page?.items.map(a=><Expand key={a.request.id} title={a.request.kind+' · '+a.state}>{()=> <ActionBody a={a} act={act}/>}</Expand>)}<Pagination previous={cursors.length>1} next={page?.next} onPrevious={()=>setCursors(cursors.slice(0,-1))} onNext={()=>page?.next&&setCursors([...cursors,page.next])}/></section>;}
function ActionRecord({id,act}:{id:string;act:Act}){const {value}=useResource<Action>('/actions/'+id,e=>e.entity===id);return value?<ActionBody a={value} act={act}/>:<p>Loading check…</p>;}
function ActionBody({a,act}:{a:Action;act:Act}){const [output,setOutput]=useState(false);return <>{a.request.kind==='model.choose' && <p>{a.request.source==='api'?'Operator model choice':'Persona model choice'}</p>}<pre>{JSON.stringify(a.request.args,null,2)}</pre>{a.error&&<p role="alert">{a.error}</p>}<pre>{JSON.stringify(a.result,null,2)}</pre>{a.request.kind==='exec'&&<><button onClick={()=>setOutput(!output)}>{output?'Close output':'Follow output'}</button>{a.state==='running'&&<button class="secondary" onClick={()=>act('job.cancel',{id:a.request.id})}>Cancel job</button>}{output&&<Output id={a.request.id}/>}</>}</>;}
function Output({id}:{id:string}){const [text,setText]=useState('');const [done,setDone]=useState(false);const offset=useRef(0);useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const r=await request<any>(`/actions/${id}/output?offset=${offset.current}`,{signal:c.signal});offset.current=r.offset;setText(t=>(t+r.text).slice(-65536));setDone(!!r.receipt?.done);if(!r.receipt?.done&&!c.signal.aborted)timer=setTimeout(load,350);}catch(e){if(!c.signal.aborted)setText((e as Error).message);}};load();return()=>{c.abort();clearTimeout(timer);};},[id]);return <section><pre class="output">{text||'Waiting for output…'}</pre><small>{done?'Job completed.':'Following output. Closing this view does not cancel work.'}</small></section>;}
function Revisions({id}:{id:string}){const [cursors,setCursors]=useState([0]);const {value:page}=useResource<Page<Entity>>(`/records/${id}/revisions?after=${cursors.at(-1)}&limit=10`,e=>e.entity===id);return <>{page?.items.map((r,i)=><Expand key={r.revision+':'+i} title={'Revision '+r.revision+' · '+r.updated}>{()=> <pre>{JSON.stringify(r.data,null,2)}</pre>}</Expand>)}<Pagination previous={cursors.length>1} next={page?.next} onPrevious={()=>setCursors(cursors.slice(0,-1))} onNext={()=>page?.next&&setCursors([...cursors,page.next])}/></>;}
