import { render } from 'preact';
import { lazy, Suspense } from 'preact/compat';
import { useEffect, useRef, useState } from 'preact/hooks';
import { connect, data, label, operate, request, short, token, blob, type Entity, type Action, type Detail, type Model, type Snapshot } from './api';
import './style.css';
const Viewer = lazy(() => import('./Viewer'));
const pages = ['Work', 'Personas', 'Environments', 'Learning', 'Network'] as const;
type Page = typeof pages[number];
function Status({ value }: { value: string }) { return <span class={'status ' + value}><i />{value || 'Waiting'}</span>; }
function Portrait({ id, name }: { id?: string; name: string }) {
  const [url, setURL] = useState('');
  useEffect(() => { if (!id) return; const c = new AbortController(); let u = ''; let closed = false; blob(id, c.signal, () => {}).then(b => { if (!closed) { u = URL.createObjectURL(b); setURL(u); } }).catch(() => {}); return () => { closed = true; c.abort(); if (u) URL.revokeObjectURL(u); }; }, [id]);
  return url ? <img class="portrait" src={url} alt={name + ', authored portrait'} /> : <div class="portrait empty" aria-label="Portrait not authored">◌</div>;
}
function App() {
  const [connected, setConnected] = useState(!!token); const [page, setPage] = useState<Page>('Work'); const [snapshot, setSnapshot] = useState<Snapshot>(); const [error, setError] = useState(''); const [selected, setSelected] = useState<string>(); const [artifact, setArtifact] = useState<string>(); const [form, setForm] = useState(''); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [receive, setReceive] = useState(false); const [models, setModels] = useState<Model[]>([]); const [epoch, setEpoch] = useState(0);
  const refresh = () => setEpoch(x => x + 1);
  useEffect(() => { if (!connected) return; const c = new AbortController(); let timer: ReturnType<typeof setTimeout>; const load = async () => { try { setSnapshot(await request<Snapshot>('/snapshot', { signal: c.signal })); setError(''); } catch (e) { if (!c.signal.aborted) setError((e as Error).message); } finally { if (!c.signal.aborted) timer = setTimeout(load, 1500); } }; load(); return () => { c.abort(); clearTimeout(timer); }; }, [connected, epoch]);
  useEffect(() => { if (!connected) return; const c = new AbortController(); request<Model[]>('/models', { signal: c.signal }).then(setModels).catch(e => { if (!c.signal.aborted) setError(e.message); }); return () => c.abort(); }, [connected]);
  const records = snapshot?.records || []; const of = (kind: string) => records.filter(r => r.kind === kind); const find = (id: string) => records.find(r => r.id === id); const people = of('persona'); const places = of('environment'); const runs = of('run');
  const kinds: { [key in Page]: string } = { Work: 'work', Personas: 'persona', Environments: 'environment', Learning: 'document', Network: 'transfer' };
  const items = of(kinds[page]).filter(r => `${label(r)} ${short(data(r), 10000)}`.toLowerCase().includes(query.toLowerCase()));
  async function act(kind: string, args: unknown, actor = '', run = '') { setBusy(true); setError(''); try { const a = await operate(kind, args, actor, run); refresh(); return a; } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (!connected) return <main class="connection"><div class="brand-mark">a<span>p</span></div><h1>A place for minds<br />to make things.</h1><p>Connect to your AI Personas node to follow its work.</p><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); connect(String(f.get('token'))); setConnected(true); }}><label>Node token<input name="token" type="password" required autoComplete="off" placeholder="Found in your node’s token file" /></label><button>Connect to node →</button></form><small>Personas work directly on the host running this node.</small></main>;
  return <div class="shell"><aside class="sidebar"><a class="brand" href="#" onClick={() => setPage('Work')}><span class="brand-mark">a<span>p</span></span><span>AI Personas<small>A continuing place</small></span></a><nav aria-label="Main navigation">{pages.map((name, i) => <button key={name} aria-label={name} class={page === name ? 'active' : ''} onClick={() => { setPage(name); setSelected(undefined); setForm(''); setQuery(''); }}><span class="nav-icon">{['▤', '◉', '▦', '◇', '⌁'][i]}</span>{name}{name === 'Work' && <span class="nav-count">{of('work').length}</span>}</button>)}</nav><div class="sidebar-bottom"><span class="live-dot" />{error ? 'Connection needs attention' : 'Connected to your node'}<small>{runs.filter(r => data(r).status === 'running').length} personas working</small><button class="quiet" onClick={() => { connect(''); setConnected(false); }}>Disconnect view</button></div></aside>
    <main class="main"><header class="topbar"><span>YOUR WORKSPACE</span><div class="live-label"><span class="live-dot" />Live activity</div></header><div class="page-heading"><div><p class="eyebrow">{({ Work: 'Ideas into useful work', Personas: 'Identity that continues', Environments: 'Room to work together', Learning: 'What stays with a persona', Network: 'Work across nodes' })[page]}</p><h1>{page}</h1><p class="subtitle">{({ Work: 'Follow the work, from the first question to the evidence.', Personas: 'Character, choices, and experience, carried from one task to the next.', Environments: 'Shared places, authored by the personas who use them.', Learning: 'Retained documents and the context personas choose to carry.', Network: 'Connected peers, messages, and the progress of shared artifacts.' })[page]}</p></div>{page !== 'Learning' && <button class="primary" onClick={() => setForm(page)}>+ {({ Work: 'New work', Personas: 'New persona', Environments: 'New environment', Network: 'Connect peer' } as any)[page]}</button>}</div>
    {error && <div class="error" role="alert">{error}<button class="quiet" onClick={refresh}>Retry</button></div>}
    {form && <CreateForm kind={form} models={models} people={people} places={places} busy={busy} close={() => setForm('')} act={act} />}
    {page === 'Network' && <><NetworkPanel epoch={epoch} /><button class="secondary" onClick={() => setReceive(true)}>Receive a shared artifact</button>{receive && <ReceiveForm act={act} close={() => setReceive(false)} />}</>}
    <div class="section-tools"><div>{items.length} {page === 'Learning' ? 'document versions' : page.toLowerCase() === 'work' ? 'work items' : page.toLowerCase()}</div><input class="search" aria-label="Filter current view" placeholder="Find in this view…" value={query} onInput={e => setQuery(e.currentTarget.value)} /></div>
    {!snapshot ? <div class="empty-state">Connecting to the current workspace…</div> : items.length === 0 ? <div class="empty-state"><span class="empty-symbol">{page === 'Work' ? '↗' : '◌'}</span><h2>{query ? 'No matching records' : ({ Work: 'What would you like to work on?', Personas: 'Every persona starts fresh.', Environments: 'Make space for shared work.', Learning: 'Learning will appear as it is retained.', Network: 'No artifact transfers yet.' })[page]}</h2><p>{page === 'Work' ? 'Create a persona and an environment, then give them a useful intention.' : 'Names, imagery, and learning appear when personas author them.'}</p></div> : <div class={'cards ' + page.toLowerCase()}>{items.map(r => { const d = data(r); const workers = runs.filter(run => run.scope === r.id); return <article key={r.id} class="card"><div class="card-top">{page === 'Personas' ? <Portrait id={d.portrait} name={label(r)} /> : page === 'Environments' ? <Portrait id={d.image} name={label(r)} /> : <span class="card-glyph">{page === 'Learning' ? '◇' : page === 'Network' ? '⇄' : '↗'}</span>}<span class="micro">{page === 'Learning' ? `Version ${r.id.slice(0, 6)}` : r.created.slice(0, 10)}</span></div><button class="card-title" onClick={() => setSelected(r.id)}>{label(r)}</button><p class="card-summary">{short(d.character || d.description || d.brief || d.title || d.name || (page === 'Personas' ? 'Character has not been authored yet.' : page === 'Network' ? d.peer : ''))}</p>
      {page === 'Work' && <div class="contributors">{(d.personas || []).map((p: string) => <span>{label(find(p))}</span>)}</div>}
      {page === 'Learning' && <p class="micro">Retained by {label(find(d.owner))}{people.some(p => (data(p).selected || []).includes(r.id)) && <span class="selected-tag">Selected context</span>}</p>}
      {page === 'Network' && <><progress value={d.bytes} max={d.total || 1} /><p class="micro">{d.bytes.toLocaleString()} / {d.total.toLocaleString()} bytes</p>{d.status === 'running' && <button class="quiet" onClick={() => act('transfer.cancel', { id: r.id })}>Cancel transfer</button>}{d.received_artifact && <button onClick={() => setArtifact(d.received_artifact)}>Open artifact</button>}</>}
      <footer>{d.status ? <Status value={d.status} /> : <span class="micro">{page === 'Personas' ? `${d.provider} / ${d.model}` : page === 'Environments' ? (d.author ? `Authored by ${label(find(d.author))}` : 'Awaiting authorship') : label(find(d.environment || r.scope))}</span>}<button class="text-button" onClick={() => setSelected(r.id)}>Open details ↗</button></footer>{workers.length > 0 && <div class="run-summary">{workers.map(run => <span><i class={'state-dot ' + data(run).status} />{label(find(data(run).persona))} · {data(run).status}</span>)}</div>}</article>; })}</div>}
    <footer class="page-footer">A place for persistent identity, shared learning, and useful work.<span>{snapshot?.contract}</span></footer></main>
    {selected && <DetailPanel key={selected} id={selected} records={records} open={setSelected} artifact={setArtifact} close={() => setSelected(undefined)} act={act} epoch={epoch} />}
    {artifact && <Suspense fallback={<div class="overlay"><div class="viewer">Opening viewer…</div></div>}><Viewer id={artifact} close={() => setArtifact(undefined)} /></Suspense>}
  </div>;
}
type Act = (kind: string, args: unknown, actor?: string, run?: string) => Promise<Action | undefined>;
function CreateForm({ kind, models, people, places, busy, close, act }: { kind: string; models: Model[]; people: Entity[]; places: Entity[]; busy: boolean; close: () => void; act: Act }) {
  return <form class="create-panel" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); let a; if (kind === 'Personas') { const m = models[Number(f.get('model'))]; a = await act('persona.create', { provider: m.provider, model: m.id }); } else if (kind === 'Environments') a = await act('environment.create', {}); else if (kind === 'Network') a = await act('peer.connect', { address: f.get('address') }); else a = await act('work.create', { title: f.get('title'), brief: f.get('brief'), environment: f.get('environment'), personas: f.getAll('personas') }); if (a) close(); }}><header><h2>{kind === 'Work' ? 'Start with an intention' : kind === 'Personas' ? 'A fresh persona' : kind === 'Network' ? 'Connect a peer' : 'A new shared environment'}</h2><button type="button" class="quiet" onClick={close}>Close ✕</button></header>
    {kind === 'Personas' ? <><p>The persona will author its name, character, and imagery through its work.</p><label>Initial model<select name="model" required>{models.map((m, i) => <option value={i}>{m.provider} · {m.name || m.id}</option>)}</select></label></> : kind === 'Environments' ? <p>Create a shared directory on this host. Personas can give it a name, description, and image.</p> : kind === 'Network' ? <label>Peer address<input name="address" placeholder="/ip4/…/tcp/…/p2p/…" required /></label> : <><label>Short title<input name="title" required placeholder="What are we making or exploring?" /></label><label>Your instructions<textarea name="brief" required rows={5} placeholder="Describe the useful result, relevant constraints, and what would establish success." /></label><label>Environment<select name="environment" aria-label="Environment" required><option value="">Choose a place</option>{places.map(p => <option value={p.id}>{label(p)}</option>)}</select></label><fieldset><legend>Personas</legend>{people.map(p => <label class="check"><input type="checkbox" name="personas" value={p.id} />{label(p)} <small>{data(p).model}</small></label>)}{!people.length && <p>Create a persona first.</p>}</fieldset></>}
    <button disabled={busy || (kind === 'Personas' && !models.length)}>{busy ? 'Saving…' : 'Create'}</button>
  </form>;
}
function ReceiveForm({act,close}:{act:Act;close:()=>void}){const [error,setError]=useState('');return <form class="create-panel" onSubmit={async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);const shared=JSON.parse(String(f.get('descriptor')));if(!shared.peer||!shared.artifact||!shared.digest||typeof shared.size!=='number')throw new Error('The shared artifact details are incomplete.');if(shared.address&&!await act('peer.connect',{address:shared.address}))return;if(await act('transfer.start',shared))close();}catch(e){setError((e as Error).message);}}}><header><h2>Receive a shared artifact</h2><button class="quiet" type="button" onClick={close}>Close ✕</button></header><p>Paste the artifact details supplied by its owner. Both nodes must trust each other's peer identity.</p><label>Shared artifact details<textarea name="descriptor" rows={5} required placeholder="Paste the copied artifact descriptor"/></label>{error&&<p role="alert">{error}</p>}<button>Start transfer</button></form>;}
function NetworkPanel({ epoch }: { epoch: number }) { const [n, setN] = useState<any>(); useEffect(() => { const c = new AbortController(); request('/network', { signal: c.signal }).then(setN).catch(() => {}); return () => c.abort(); }, [epoch]); return <div class="network-info"><h2>This node</h2><p class="micro">{n?.id || 'Loading peer identity…'}</p>{n?.addresses.map((a: string) => <code>{a}</code>)}<p>{n?.peers.length || 0} connected peers</p></div>; }
function DetailPanel({ id, records, close, open, artifact, act, epoch }: { id: string; records: Entity[]; close: () => void; open: (id: string) => void; artifact: (id: string) => void; act: Act; epoch: number }) {
  const [detail, setDetail] = useState<Detail>(); const [error, setError] = useState(''); const [output, setOutput] = useState<string>(); const [call, setCall] = useState<string>(); const [raw, setRaw] = useState(''); const [review, setReview] = useState('');
  useEffect(() => { const c = new AbortController(); let timer: ReturnType<typeof setTimeout>; const load = async () => { try { setDetail(await request<Detail>('/records/' + id, { signal: c.signal })); } catch (e) { if (!c.signal.aborted) setError((e as Error).message); } finally { if (!c.signal.aborted) timer = setTimeout(load, 1200); } }; load(); return () => { c.abort(); clearTimeout(timer); }; }, [id, epoch]);
  useEffect(() => { if (!call) return; const c = new AbortController(); fetch('/api/calls/' + call + '/request.json', { headers: { Authorization: `Bearer ${token}` }, signal: c.signal }).then(r => r.text()).then(setRaw).catch(() => {}); return () => c.abort(); }, [call]);
  const r = detail?.record; const d = r ? data(r) : {}; const find = (id: string) => records.find(r => r.id === id); const people = records.filter(r => r.kind === 'persona');
  return <div class="drawer" role="dialog" aria-modal="true" aria-label="Record details"><header><div><p class="eyebrow">{r?.kind || 'Details'}</p><h2>{r ? label(r) : 'Loading…'}</h2></div><button class="quiet" onClick={close}>Close ✕</button></header>{error && <p role="alert">{error}</p>}{r && <div class="drawer-body">{d.status && <Status value={d.status} />}<p class="long-text">{typeof (d.character || d.description || d.brief || d.content || d.instructions || d.summary) === 'string' ? (d.character || d.description || d.brief || d.content || d.instructions || d.summary) : short(d.character, 10000)}</p>{d.note && <p class="notice">{d.note}</p>}
    {r.kind === 'persona' && <><Portrait id={d.portrait} name={label(r)} /><h3>Chosen model</h3><p>{d.provider} / {d.model}</p><h3>Carried context</h3><p class="long-text">{d.context || 'No authored context summary yet.'}</p>{(d.selected || []).map((v: string) => <button class="record-link" onClick={() => open(v)}>{label(find(v))} ↗</button>)}<form onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); const a = await act('message.send', { to: r.id, text: f.get('message') }); if (a) form.reset(); }}><label>Send an instruction<textarea name="message" required rows={3} /></label><button>Send message</button></form></>}
    {detail?.related.some(x => x.kind === 'message') && <><h3>Conversation</h3>{detail.related.filter(x => x.kind === 'message').map(m => <section class="evidence"><p class="micro">{label(find(data(m).from))} → {label(find(data(m).to))}</p><p class="long-text">{data(m).text}</p></section>)}</>}
    {detail?.related.some(x => x.kind === 'tool') && <><h3>Owned tools and skills</h3>{detail.related.filter(x => x.kind === 'tool').map(t => <details><summary>{data(t).name}</summary><p>{data(t).description}</p><p>Acquired through: {data(t).acquisition}</p><pre>{data(t).command}</pre></details>)}</>}
    {r.kind === 'environment' && <><h3>Shared work and documents</h3>{detail?.related.filter(x => x.kind === 'work' || x.kind === 'document').map(x => <button class="record-link" onClick={() => open(x.id)}>{label(x)} ↗</button>)}<form onSubmit={async e => { e.preventDefault(); const form=e.currentTarget; const f=new FormData(form); if(await act('message.send',{to:r.id,text:f.get('message'),environment:r.id}))form.reset(); }}><label>Message this environment<textarea name="message" required rows={3}/></label><button>Send message</button></form></>}
    {r.kind === 'work' && <><h3>Persona activity</h3>{detail?.related.filter(x => x.kind === 'run').map(run => <button class="record-link" onClick={() => open(run.id)}>{label(find(data(run).persona))}<Status value={data(run).status} /></button>)}</>}
    {r.kind === 'run' && <div class="button-row"><button onClick={() => act('run.resume', { id })}>Resume</button><button class="secondary" onClick={() => act('run.pause', { id })}>Pause decisions</button><button class="secondary" onClick={() => act('run.cancel', { id })}>Cancel work</button></div>}
    {detail?.related.filter(x => x.kind === 'submission').map(s => <section class="evidence"><h3>Submitted version</h3><p>{data(s).summary}</p>{data(s).artifacts?.map((a: string) => <button onClick={() => artifact(a)}>Open artifact {a.slice(0, 6)}</button>)}{data(s).documents?.map((a: string) => <button onClick={() => open(a)}>Open document {a.slice(0, 6)}</button>)}<button class="secondary" onClick={() => setReview(s.id)}>Request independent review</button></section>)}
    {review && <form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await act('review.start', { submission: review, persona: f.get('persona'), instructions: f.get('instructions') })) setReview(''); }}><label>Reviewer<select name="persona" required>{people.map(p => <option value={p.id}>{label(p)}</option>)}</select></label><label>Assessment instructions<textarea name="instructions" required rows={4} /></label><button>Start review</button></form>}
    {detail?.related.filter(x => x.kind === 'finding').map(f => <section class="evidence"><Status value={data(f).verdict} /><p class="long-text">{data(f).findings}</p><p class="micro">{data(f).checks?.length || 0} recorded checks</p></section>)}
    {detail?.related.filter(x => x.kind === 'call').length ? <><h3>Observed model usage</h3><p class="micro">Requests observed by this application. Unknown usage remains unknown.</p>{detail.related.filter(x => x.kind === 'call').map(c => <details><summary>{data(c).actual_model || data(c).requested_model} · {data(c).status}</summary><p>{data(c).summary}</p><p>{data(c).usage?.known ? `${data(c).usage.input} input · ${data(c).usage.cached} cached · ${data(c).usage.output} output tokens` : 'Usage unknown'}</p><button onClick={() => setCall(c.id)}>Inspect actual request</button>{data(c).error && <p role="alert">{data(c).error}</p>}</details>)}</> : null}
    {call && <details open><summary>Recorded model request</summary><button class="quiet" onClick={() => { setCall(undefined); setRaw(''); }}>Close request</button><pre>{raw || 'Loading…'}</pre></details>}
    {!!detail?.actions.length && <><h3>Actions and returned results</h3>{detail.actions.map(a => <details><summary><Status value={a.state} />{a.request.kind}</summary><pre>{JSON.stringify(a.request.args, null, 2)}</pre>{a.error && <p role="alert">{a.error}</p>}<pre>{JSON.stringify(a.result, null, 2)}</pre>{a.request.kind === 'exec' && <div class="button-row"><button onClick={() => setOutput(a.request.id)}>Follow output</button>{a.state === 'running' && <button class="secondary" onClick={() => act('job.cancel', { id: a.request.id })}>Cancel job</button>}</div>}</details>)}</>}
    {output && <Output id={output} close={() => setOutput(undefined)} />}
    <details><summary>Preserved versions · {detail?.revisions.length}</summary><pre>{JSON.stringify(detail?.revisions, null, 2)}</pre></details><p class="micro">{r.id}</p></div>}</div>;
}
function Output({ id, close }: { id: string; close: () => void }) { const [text, setText] = useState(''); const offset = useRef(0); useEffect(() => { const c = new AbortController(); let timer: ReturnType<typeof setTimeout>; offset.current = 0; setText(''); const tick = async () => { try { const r = await request<any>(`/actions/${id}/output?offset=${offset.current}`, { signal: c.signal }); offset.current = r.offset; setText(t => (t + r.text).slice(-150000)); } catch (e) { if (!c.signal.aborted) setText((e as Error).message); } finally { if (!c.signal.aborted) timer = setTimeout(tick, 350); } }; tick(); return () => { c.abort(); clearTimeout(timer); }; }, [id]); return <section class="output"><header><h3>Command output</h3><button class="quiet" onClick={close}>Close output</button></header><pre>{text || 'Waiting for output…'}</pre><small>Closing this view leaves the job running.</small></section>; }
render(<App />, document.getElementById('app')!);
